theme: jekyll-theme-slate
title: Workshop Modelle und KI (MoKI'22)
description: Co-Located with the Modellierung 2022 Conference in Hamburg, 27.06.2022 - 01.07.2022

plugins:
  - jekyll-relative-links
  - jekyll-redirect-from
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
